app/events/models.py
from app.extensions.database import db, CRUDMixin

class event(db.Model,CRUDMixin):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(50))
    date = db.Column(db.Integer)
    desc =db.Column(db.String(1024))

app/users/models.py
from app.extensions.database import db, CRUDMixin
from flask_login import UserMixin



class User(db.Model,CRUDMixin,UserMixin):
  id = db.Column(db.Integer, primary_key=True)
  email = db.Column(db.String(80), index=True, unique=True)
  password = db.Column(db.String(80))

app/__init__.py
#from .users import users
from . import events

app/api/__init__.py
from . import routes

app/api/routes.py
from flask import Blueprint, jsonify, request
from .services.serialize_events import serialize_events
from app.events.models import event
from os import environ


blueprint = Blueprint('api',__name__)

@blueprint.get('/api/v1/events')
def events():
    if environ.get('API_KEY') == request.header.get('X-API-KEY'):
        events=event.query.all()

        return jsonify(
         serialize_events(events)
        )
    else:
        return jsonify({'error': 'Invalid API key'}), 401

def serialize_events(events):
     events_list = []

     for event in events:
        events_list.append({
            'id' : event.id,
            'event': {
                'name': event.name,
                'date': event.date,
                'desc': event.desc,
            }
        })
     return events_list

app/app.py
from flask import Flask, Blueprint
from app.extensions.database import db, migrate
from app.extensions.authentication import login_manager
from . import events, api, users

from app.events.routes import blueprint as events_blueprint
from app.api.routes import blueprint as api_blueprint

def create_app():
  app = Flask(__name__)
  app.config.from_object('app.config')
  register_extensions(app)
  register_blueprints(app)

  return app

def register_blueprints(app: Flask):
  app.register_blueprint(events_blueprint)
  app.register_blueprint(users.routes.blueprint)
  app.register_blueprint(api_blueprint)

def register_extensions(app:Flask):
  login_manager.init_app(app)
  db.init_app(app)
  with app.app_context():
      from app.events.models import event
      db.create_all()
      migrate.init_app(app, db, compare_type=True)

app/events/routes.py
from flask import Blueprint, Flask, render_template, redirect, url_for, request, current_app
from .models import event
from app.extensions.database import db
from flask_login import login_required


blueprint = Blueprint('events/',__name__)

@blueprint.route('/events')
def get_events():
  page_number = request.args.get('page', 1, type=int)
  events_pagination = event.query.paginate(page_number, current_app.config['EVENTS_MAX_PER_PAGE'])
  return render_template('events.html', events_pagination=events_pagination)

@blueprint.route('/register', methods=('GET','POST'))
@login_required
def post_events():

  if request.method == 'POST':
    new_event=event(
      name=request.form['event'],
      date=request.form['event_date'],
      desc=request.form['event_discription']
    )
    print(db)
    db.session.add(new_event)
    db.session.commit()
    print("new event is saved", new_event)
    return redirect(url_for('events/.get_events'))
  return render_template('register.html')

@blueprint.post('/register/delete')
@login_required
def delete_event():
  event_id = request.form['event_id']
  print(event_id)
  event_to_delete = event.query.filter_by(id=event_id).first()
  print(event_to_delete)
  db.session.delete(event_to_delete)
  db.session.commit()

  return redirect('/events')


@blueprint.route('/edit_event/<id>', methods=('GET','POST'))
def post_events_edit(id):
  if request.method == 'POST':
    update_event=event.query.filter_by(id=id).first()

    update_event.name=request.form['event']
    update_event.date=int(request.form['event_date']) 
    update_event.desc=request.form['event_discription']

    db.session.add(update_event)
    db.session.commit()

    print("new event is saved", update_event)
    return redirect(url_for('events/.get_events'))
  print(id)
  curr_event = event.query.filter_by(id=id).first()
  return render_template('edit_event.html', event=curr_event)

@blueprint.route('/')
def index():
  return render_template('index.html')

app/users/__init__.py
from . import models, routes

app/users/routes.py
from flask import Blueprint, render_template, request, url_for,redirect
from app.users.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user
blueprint = Blueprint('user', __name__)


@blueprint.get('/new_acc')
def get_new_acc():
   return render_template('new_acc.html')

@blueprint.post('/new_acc')
def post_new_acc():
  try:
    if request.form.get('password') != request.form.get('password_confirmation'):
      raise Exception('The password confirmation must match the password.')
    elif User.query.filter_by(email=request.form.get('email')).first():
      raise Exception('The email adress is already registered')

    user = User(
      email=request.form.get('email'),
      password=generate_password_hash(request.form.get('password'))
    )
    user.save()

    login_user(user)
    return redirect(url_for('events.events'))
  except Exception as error_meassage:
    error= error_meassage or 'An error ocurred while creating a user. Please make sure to enter valid data'
    return render_template('new_acc.html',error=error)

@blueprint.get('/login')
def get_login():
 return render_template('login.html')

@blueprint.post('/login')
def post_login():
  try:
    user = User.query.filter_by(email=request.form.get('email')).first()

    if not user:
      raise Exception('No user with the given email address was found.')
    elif not check_password_hash(user.password, request.form.get('password')):
      raise Exception('The password does not appear to be correct.')
    login_user(user)
    return redirect(url_for('events/.get_events'))
  except Exception as error_message:
    error = error_message or 'An error occured while logging in. Please verify your email and password'
    return render_template('login.html', error=error)

@blueprint.get('/logout')
def logout():
  logout_user()

  return redirect(url_for('user.get_login'))

app/templates/base.html
<!DOCTYPE html>
<head>
  <html lang="en">
<head>
  {% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  {% endblock %}
</head>
</head>
<body>
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                
                <menuitem><a href="{{ url_for('events/.get_events') }}"><button type="button">Events</button></a></menuitem>
                <menuitem><a href="{{ url_for('events/.post_events') }}"><button type="button">Register</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2></h2>
        
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
</body>

app/templates/edit_event.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events/.index') }}"><button type="button">Home</button></a></menuitem>
                <menuitem><a href="{{ url_for('events/.get_events') }}"><button type="button">Events</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Edit your event</h2>
        <form method="POST" action="/edit_event/{{event.id}}">
          <p>
            <div>
              <label for="event"></label>
              <input type="text" name="event" id="event" placeholder="your event name" value="{{event.name}}">
            </div>
          </p>
          <p>
            <div>
              <label for="event_date"></label>
              <input type="integer" name="event_date" id="event_date"  placeholder="dd.mm.yyyy" >
            </div>
          </p>
          <p>
            <div>
              <label for="event_discription"></label>
              <input type="text" name="event_discription" id="event_discription" placeholder="your event discription" value="{{event.desc}}">
            </div>
          </p>
          <p>
            <div>
              <input type="submit" value="update">
            </div>
          </p>  
        </form>
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
</body>

app/templates/error.html
{% if error %}
  <p style="color: tomato;">{{ error }}</p>
{% endif %}

app/templates/events.html
<!DOCTYPE html>
<head>
  <link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/main.css') }}"
  />
</head>
<body>
  <header>
    <h1>YSOCIAL</h1>
    <nav>
      <menu>
        <menuitem><a href="{{ url_for('events/.index') }}">
          <button type="button">Home</button></a>
        </menuitem>
        {% if current_user.is_authenticated %}

        <menuitem><a href="{{ url_for('user.logout') }}">
          <button type="button">Logout</button></a>
        </menuitem>
        <small> Logged in as {{ current_user.email }} </small>
        {% else %}
        <menuitem><a href="{{ url_for('user.get_login') }}">
          <button type="button">Login</button></a>
        </menuitem>
        {% endif %}
      </menu>
    </nav>
  </header>
  <div class="main">
    <div class="eventclass">
      
      {% for event in events_pagination.items %}
        
        <p>{{event.name}}
           {{event.date}}
           {{event.desc}}
          <form method="POST" action="/register/delete">
            <input type="hidden" name="event_id" id="event_id" value="{{event.id}}">
            <button type="submit" value="submit">delete</button>
          </form>
          <button><a href="/edit_event/{{event.id}}" class="">edit</a></button>
        </p>
      {%endfor%}
    
      <!-- <nav>
        <p>
          {% if events_pagination.prev_num %}
          <a href="{{url_for('events.events', page=events_pagination.pref_num) }}"
            >Previous Page</a
          >
          {%else%}
          <small>
            <span>Previous Page</span>
            {% endif %}
            <span> - </span>
            {% if events_pagination.next_num %}
            <a
              href="{{ url_for('events.events', page=events_pagination.next_num) }}"
              >Next Page</a
            >
            {% else%}
            <span>Next Page</span>
          </small>
          {% endif %}
        </p>
      </nav> -->
      <p>
        <a href="{{ url_for('events/.post_events') }}"><button type="button">Register your event</button></a>
     </p>
    </div>
  </div>
  
</body>

app/templates/index.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events/.get_events') }}"><button type="button">Events</button></a></menuitem>
                {% if current_user.is_authenticated %}
                
                  <menuitem><a href="{{ url_for('user.logout') }}"><button type="button">Logout</button></a></menuitem>
                  <small>
                    Logged in as {{ current_user.email }}
                  </small>
                {% else %}
                  <menuitem><a href="{{ url_for('user.get_login') }}"><button type="button">Login</button></a></menuitem>
                {% endif %}
            </menu>
        </nav>
    </header>
    <div class="slider">
      <div class="slides">
        <input type="radio" name="radio-btn" id="radio1">
        <input type="radio" name="radio-btn" id="radio2">
        <input type="radio" name="radio-btn" id="radio3">
        <input type="radio" name="radio-btn" id="radio4">

        <div class="slide first">
          <img src="static/images/eventbild1.jpg" alt='eventbild1'>
        </div>
        <div class="slide">
          <img src="static/images/eventbild2.jpg" alt='eventbild2'>
        </div>
        <div class="slide">
          <img src="static/images/eventbild3.jpg" alt='eventbild3'>
        </div>
        <div class="slide">
          <img src="static/images/eventbild4.jpg" alt='eventbild4'>
        </div>

        <div class="navigation-auto">
          <div class="auto-btn1"></div>
          <div class="auto-btn2"></div>
          <div class="auto-btn3"></div>
          <div class="auto-btn4"></div>
        </div>
      </div>
    </div>
    <script type="text/javascript">
      var counter = 1;
      setInterval(function(){
        document.getElementById('radio'+ counter).checked = true;
        counter++;
        if(counter > 4){
          counter = 1;
        }
      }, 5000);
    </script>
    <div class="main">
      <div class="register">
          <h2>Start to explore your area and connect with people</h2>
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
</body>

app/templates/login.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
{% block body %}
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events/.index') }}"><button type="button">Home</button></a></menuitem>
                <menuitem><a href="{{ url_for('events/.get_events') }}"><button type="button">Events</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Login</h2>
        <form method="POST">
          
            <div>
              <p>
              <label for="email"></label>
              <input type="email" name="email" id="email" required placeholder="email">
            </p>
            </div>
            <div>
              <p>
              <label for="password"></label>
              <input type="password" name="password" id="password" required placeholder="password">
            </p>
            </div>
           
            <input type="submit" value="Login">
            <p><a href="{{ url_for('user.get_new_acc') }}"><button type="button">Register a new account</button></a></p>
        </form>
        {% if error %}
        <p style="color: tomato;">{{ error }}</p>
        {% endif %}
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
  {% endblock %}

app/templates/new_acc.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
{% block body %}
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events/.index') }}"><button type="button">Home</button></a></menuitem>
                <menuitem><a href="{{ url_for('events/.get_events') }}"><button type="button">Events</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Register</h2>
        <form method="POST">
          
            <div>
              <p>
              <label for="email"></label>
              <input type="email" name="email" id="email" required placeholder="email">
              </p>
            </div>
            <div>
              <p>
              <label for="password"></label>
              <input type="password" name="password" id="password" required placeholder="password">
              </p>
            </div>
            <div>
              <p>
                <label for="password_confirmation"></label>
                <input type="password" name="password_confirmation" id="password_confirmation" required placeholder="password confirmation">
              </p>
            </div>
           
            <input type="submit" value="Sign Up">
        </form>
      {% if error %}
      <p style="color: tomato;">{{ error }}</p>
      {% endif %}     
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
  {% endblock %}

app/templates/register.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events/.index') }}"><button type="button">Home</button></a></menuitem>
                {% if current_user.is_authenticated %}

                <menuitem><a href="{{ url_for('user.logout') }}">
                  <button type="button">Logout</button></a>
                </menuitem>
                <small> Logged in as {{ current_user.email }} </small>
                {% else %}
                <menuitem><a href="{{ url_for('events/.get_events') }}"><button type="button">Events</button></a></menuitem>
                {% endif %}
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Register your event</h2>
        <form method="POST" action="/register">
          <p>
            <div>
              <label for="event"></label>
              <input type="text" name="event" id="event" required placeholder="your event name">
            </div>
          </p>
          <p>
            <div>
              <label for="event_date"></label>
              <input type="integer" name="event_date" id="event_date" required placeholder="dd.mm.yyyy">
            </div>
          </p>
          <p>
            <div>
              <label for="event_discription"></label>
              <input type="text" name="event_discription" id="event_discription" required placeholder="your event description">
            </div>
          </p>
          <p>
            <div>
              <input type="submit" value="register">
            </div>
          </p>  
        </form>
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
</body>

app/templates/users/login.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
{% block body %}
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events.index') }}"><button type="button">Home</button></a></menuitem>
                <menuitem><a href="{{ url_for('events/.get_events') }}"><button type="button">Events</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Login</h2>
        <form method="POST">
          
            <div>
              <p>
              <label for="email">Email</label>
              <input type="email" name="email" id="email" required>
            </p>
            </div>
            <div>
              <p>
              <label for="password">Password</label>
              <input type="password" name="password" id="password" required>
            </p>
            </div>
           
            <input type="submit" value="Login">

        </form>
        {% if error %}
        <p style="color: tomato;">{{ error }}</p>
        {% endif %}
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
  {% endblock %}

app/templates/users/register_acc.html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>
{% block body %}
  <div id="content" class="page">
    <header>
        <h1>YSOCIAL</h1>
        <nav>
            <menu>
                <menuitem><a href="{{ url_for('events.index') }}"><button type="button">Home</button></a></menuitem>
                <menuitem><a href="{{ url_for('events.get_events') }}"><button type="button">Events</button></a></menuitem>
            </menu>
        </nav>
    </header>
    <div class="main">
      <div class="register">
          <h2>Register</h2>
        <form method="POST">
          
            <div>
              <label for="email">Email</label>
              <input type="email" name="email" id="email" required>
            </div>
            <div>
              <label for="password">Password</label>
              <input type="password" name="password" id="password" required>
            </div>

            <div>
                <label for="password_confirmation">Password Confirmation</label>
                <input type="password" name="password_confirmation" id="password_confirmation" required>
            </div>
           
            <input type="submit" value="Sign Up">
        </form>
      {% if error %}
      <p style="color: tomato;">{{ error }}</p>
      {% endif %}     
      </div>
    </div>
    <div class="footer">
      <p class="footer writing">Joy is social!</p>
    </div>
  </div>
  {% endblock %}